name: Publish Website to Web Hosting
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: 2023/
          local-dir: ./dist
          port: 21
          exclude: |
            **/.html*
            **/.js*
            **/.css*
            **/.jpg*
            **/.gif*
            **/.png*
            **/.svg*
            **/.woff*
            **/.woff2*
            **/.gif*
            **/.mp3*
            **/.mp4*
            **/.glb*
